# Custom rules for dart static analysis

include: package:pedantic/analysis_options.yaml

# linter:
#   rules:
#     - camel_case_types
#     - empty_constructor_bodies
#     - constant_identifier_names

linter:
  rules:
    curly_braces_in_flow_control_structures : false
