name: starter_kit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  analyzer: "0.37.0"
  dio: "2.1.13"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: "1.5.0"

flutter:
  uses-material-design: true

  # assets:
